nodes:
  # Core TensorRT nodes
  comfyui-tensorrt:
    name: "ComfyUI TensorRT"
    url: "https://github.com/yondonfu/ComfyUI_TensorRT.git"
    branch: "quantization_with_controlnet_fixes"
    type: "tensorrt"

  comfyui-depthanything-tensorrt:
    name: "ComfyUI DepthAnything TensorRT"
    url: "https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt"
    type: "tensorrt"

  comfyui-streamdiffusion:
    name: "ComfyUI StreamDiffusion"
    url: "https://github.com/pschroedl/ComfyUI-StreamDiffusion"
    branch: "main"
    type: "tensorrt"

  comfyui-fasterliveportrait:
    name: "ComfyUI FasterLivePortrait"
    url: "https://github.com/pschroedl/ComfyUI-FasterLivePortrait.git"
    branch: "main"
    type: "tensorrt"


  comfyui-torch-compile:
    name: "ComfyUI Torch Compile"
    url: "https://github.com/yondonfu/ComfyUI-Torch-Compile"
    type: "optimization"


  comfyui-stream-pack:
    name: "ComfyUI Stream Pack"
    url: "https://github.com/livepeer/ComfyUI-Stream-Pack"
    branch: "main"
    type: "utility"
